### ISSUE TITLE
[Bounty] Fix in-call audio on Bluetooth headset on CAF device, running AOSP GSI Pie

### ISSUE THREAD

**Issue by phhusson** [phhusson/treble_experimentations#374] opened 2019-01-22 16:36 UTC
The reference device which will be used for this bug bounty is a Razer Phone,, 8.1 vendor, running an SFR (French operator) single SIM, with a Parrot Zik headset.
This bounty will be considered fulfilled if the submitter provides sources that can be integrated into Phh-Treble GSI Pie that fixes this test-case.

Hopefully, this will fix this issue on every existing CAF devices.

Current total: 45$
Subdivision:
- @phhusson 5$
- @linuxct 10$
- @willowtip 20$ (tested on Mi Mix 3)
- @Koenkk 10$ (tested on Mi 9)

**Comment by phhusson** [comment] 2019-01-22 16:37
I'm in for this bug bunty for 5$

**Comment by androidguy99** [comment] 2019-01-22 19:52
How bout this?
https://github.com/AospExtended/platform_system_bt/commit/72136b3f8c1f82601f87c5d8e4d7bd38bbba3a32

**Comment by androidguy99** [comment] 2019-01-22 22:01
@linuxct how about if you add this overlay to overlays
https://github.com/AospExtended-Devices/device_motorola_potter/commit/f6ba0a698bc9efaec46f8ee6251740d396a4fcf0#diff-e0a3646285a5f4f89d0d2f1cd05c0458
I don't see it already unless I'm missing it.

**Comment by linuxct** [comment] 2019-01-22 22:47
> @linuxct how about if you add this overlay to overlays
> [AospExtended-Devices/device_motorola_potter@f6ba0a6#diff-e0a3646285a5f4f89d0d2f1cd05c0458](https://github.com/AospExtended-Devices/device_motorola_potter/commit/f6ba0a698bc9efaec46f8ee6251740d396a4fcf0#diff-e0a3646285a5f4f89d0d2f1cd05c0458)
> I don't see it already unless I'm missing it.

Already had that [in my phone's overlay](https://github.com/linuxct/vendor_hardware_overlay/commit/12f3720cb112494e2feb4878ee694ea6bf43bb40#diff-3e24cbc58be140229e2731df7c8fbec8R39) since a long ago - Still no results.

**Comment by AndroPlus-org** [comment] 2019-01-23 12:12
So my issue became "duplicate" lol
https://github.com/phhusson/treble_experimentations/issues/344

On non-GSI build I confirmed deleting A2DP related strings from xml and binding it
(on init
    mount none /system/etc/audio_policy_configuration.xml /vendor/etc/audio/audio_policy_configuration.xml bind
) fixed in-call audio in BT headset.
I also created Magsik module to do the same thing and it worked, but I couldn't get it to work with rw-system.sh.
Maybe script running timing problem?

**Comment by phhusson** [comment] 2019-01-23 12:22
already tried it. It doesn't work. I'm guessing your non-gsi isalso not
aosp, but caf based

Le mer. 23 janv. 2019 à 13:12, AndroPlus <notifications@github.com> a
écrit :

**Comment by guglicap** [comment] 2019-01-29 20:00
could this also fix #347?

**Comment by phhusson** [comment] 2019-01-29 20:02
Nope

**Comment by willowtip** [comment] 2019-02-08 02:28
put me in for $20 towards a fix for this on Mi Mix 3

**Comment by byackee** [comment] 2019-03-19 10:32
Hi, how I donate for this issue plz ?

**Comment by laptapper1** [comment] 2019-03-23 14:38
I'm in with 50€ if someone fix the Bluetooth for pie on elephone u pro

**Comment by rafyvitto** [comment] 2019-03-31 15:23
Deleting /vendor/etc/a2dp_audio_policy_configuration.xml fixed inCall Audion on my Asus zenfone 5z.

**Comment by linuxct** [comment] 2019-03-31 15:27
We are talking about Bluetooth in-call audio, not the earpiece audio, right? @rafyvitto


On Sun, Mar 31, 2019 at 5:23pm, rafyvitto < notifications@github.com [notifications@github.com] > wrote:
Deleting /vendor/etc/a2dp_audio_policy_configuration.xml fixed inCall Audion on my Asus zenfone 5z.

**Comment by rafyvitto** [comment] 2019-03-31 15:32
Bluetooth in-call audio correct. @linuxct

**Comment by phhusson** [comment] 2019-03-31 15:47
@rafyvitto on my AOSP?

**Comment by rafyvitto** [comment] 2019-03-31 15:54
@phhusson RR v7.0 based on your pie v110 aosp gsi yes.

**Comment by phhusson** [comment] 2019-03-31 16:52
yeah, no. I'm pretty confident it won't work on my ROM. RR is CAF-based.

**Comment by rafyvitto** [comment] 2019-03-31 23:34
@phhusson  I see was not  aware RR was based on caf.

**Comment by phhusson** [comment] 2019-04-01 06:36
@rafyvitto could you get me logcat on RR when it works?

Do `adb logcat -c; adb logcat > logs.txt` start the call, switch to speaker and back to bluetooth

**Comment by voodoojonny** [comment] 2019-04-03 20:52
Deleting vendor/etc/a2dp_audio_policy_configuration doesn´t fix in-call audio on bluetooth headset - tried with pie and oreo vendor

**Comment by voodoojonny** [comment] 2019-04-04 13:53
https://forum.xda-developers.com/showpost.php?p=79197462&postcount=7
Thanks to @AndroPlus-org bt incall audio works now.
Deleting the line: mount -o bind /mnt/phh/empty_dir /vendor/etc/audio || true
in system/bin/rw-system.sh fixed it! Nothing else to do.
That means, it can be included in treble-roms quite easily. Nothing in vender needs to be changed!
@phhusson do you still need the logs?

**Comment by phhusson** [comment] 2019-04-04 13:55
It doesn't work on AOSP.

**Comment by rafyvitto** [comment] 2019-04-04 13:58
@phhusson just saw your message, il do it today after work and post it here.

**Comment by laptapper1** [comment] 2019-04-04 14:29
For my elephone u pro there's this solution for working in call Bluetooth :
You have to extract stock /vendor/etc/audio/audio_policy_configuration.xml and delete A2DP related section like this:
https://github.com/PixelExperience-D...e5f1183e73e9ff
then replace it (by root explorer or creating magisk module

Additional 
Deleting the line: mount -o bind /mnt/phh/empty_dir /vendor/etc/audio || true
in system/bin/rw-system.sh

https://forum.xda-developers.com/showpost.php?p=79191978&postcount=5

**Comment by AndroPlus-org** [comment] 2019-04-04 21:40
@laptapper1 again it doesn't work on AOSP... It works only on CAF based custom roms.

**Comment by rafyvitto** [comment] 2019-04-05 01:54
@phhusson https://pastebin.com/RfUiWWrK here it is.

**Comment by laptapper1** [comment] 2019-04-05 06:00
@AndroPlus-org
Yes and the bounty title is written that we're talking about CAF !?

**Comment by linuxct** [comment] 2019-04-05 06:13
@laptapper1 This issue is regarding Bluetooth In-Call audio for CAF based devices running AOSP, not a CAF device tree. Thus, ROMs based on it are excluded.

**Comment by Koenkk** [comment] 2019-05-16 12:40
Please also add me to the list (Xiaomi Mi 9) for 10 dollars. 

@phhusson maybe it's a nice thing to add a 'Bounty' label so bounty hunters can easily find this.

**Comment by darkestDark** [comment] 2019-06-20 17:17
everytime i am looking at this shit... i am falling over the value for a2dp sink. in aosp its disabled by default in bools value of bluetooth.apk. 
Code Aurora Devices seems to use it...
https://gitlab.com/Codeaurora/platform_system_bt/tree/aosp-new/master/btif/include

But my shitty apk tool isnt able to resign the change apk with system key... and in the end my free time for testing its over... and only changeing system prop isnt enough at all... someone tested this way already? so i wont waste time with this...?

**Comment by willowtip** [comment] 2019-06-20 18:55
withdrawing my bounty on this.  i moved on from the mix 3.  good luck.

**Comment by scottvpb** [comment] 2019-07-27 01:50
I don't know if there is any to make Phh 9.0 rom work with in call bluetooth audio, but if a future version had in call audio I would happily pass along $25 USD. IM running it on a Lenovo K5 Pro as a daily driver and bluetooth music and notifications works just fine.

**Comment by penn5** [comment] 2019-07-28 21:18
I think I've cracked it. Wait till I get home next week and I'll test then release the fix

**Comment by scottvpb** [comment] 2019-07-28 21:43
Thanks for the update.  I'll stand by

**Comment by penn5** [comment] 2019-07-29 17:18
Success in my mi9
Tested on Descendant (non-CAF)
A2DP did not encounter any regressions
Volume control works normally, with separate control for a2dp Vs sco
Only issue is currently the fix is manual. Later I'll automate it but currently I'm in a tiny village in Scotland with no laptop even. 
Pm me t.me/hackintosh5 for the fix for testing, or wait

**Comment by penn5** [comment] 2019-07-29 20:05
Confirmed on Lenovo K5 Pro

**Comment by scottvpb** [comment] 2019-07-29 20:13
the fix worked well on the Lenovo K5 Pro thanks @penn5

**Comment by penn5** [comment] 2019-07-29 21:23
@Koenkk @phhusson @linuxct calling in

Add ```<route type="mix" sink="BT SCO Headset"
                       sources="primary output,deep_buffer,compressed_offload,Telephony Rx"/>``` to your /system/etc/audio_policy_configuration.xml under the <routes> element and reboot. 
It's tested on mi9 already.

**Comment by penn5** [comment] 2019-07-30 07:37
> @rafyvitto could you get me logcat on RR when it works?
> 
> Do `adb logcat -c; adb logcat > logs.txt` start the call, switch to speaker and back to bluetooth

You were looking in the wrong place. The bug manifests while connecting the headset.

**Comment by penn5** [comment] 2019-07-30 11:37
@phhusson how do you want to implement this? Bind mount or fwk change?

**Comment by darkestDark** [comment] 2019-07-30 12:33
confirmed @ Redmi Note 7

well done!

**Comment by TheEEST** [comment] 2019-07-30 14:34
Confirmed for Lenovo S5
Great work!

**Comment by phhusson** [comment] 2019-07-30 22:26
For all people who tried @penn5 fix, and got it to work, please donate bounty to him.
Actual fix (i.e. without user needing to change /vendor) still needs to be done, but the hard work has been done by @penn5, he deserves the bounty.

If for some people @penn5's fix doesn't work, please step up, so I know it.

Since this hasn't been tested on older devices yet (i.e. Razor Phone as stated in the original issue), I'm not sure this fixes the issue for all CAF devices. So for the moment, I recommend that you give him the bounty only if you confirmed its fix works for you.

Hopefully, I'll have integrated a proper fix for next release next week, for everyone to test without editing /vendor.

**Comment by phhusson** [comment] 2019-07-31 11:39
fwk change
There is an example of such a hack at:
https://github.com/phhusson/platform_frameworks_av/commit/36fa5861004009f781da34904c02fadb2ff60a6a

**Comment by Koenkk** [comment] 2019-07-31 18:29
@penn5 what's your paypal?

**Comment by penn5** [comment] 2019-07-31 20:25
paypal.me/hackintosh5

**Comment by Koenkk** [comment] 2019-08-01 16:38
@penn5 send!

**Comment by phhusson** [comment] 2019-08-05 16:13
fwiw, I confirmed @penn5's fix on Mi 9 and Mi Mix 3, so I'm pretty confident it's right.
I've included it ( https://github.com/phhusson/platform_frameworks_av/commit/aeba25b0e1cab4798869b1d41d8f0780e81e95d0 ).
It will be available in my next release.


@willowtip @Koenkk don't forget to tip @penn5 when you confirm it works for you on next version.

**Comment by penn5** [comment] 2019-08-05 16:50
> @willowtip @Koenkk don't forget to tip @penn5 when you confirm it works for you on next version.

Or face eternal shame :D

**Comment by penn5** [comment] 2019-08-05 16:54
@laptapper1 can you test it? Im interested if Kyro is the same

**Comment by penn5** [comment] 2019-08-05 16:58
@laptapper1 can you test it? Im interested if Kyro is the same

**Comment by laptapper1** [comment] 2019-08-06 06:34
@penn5
I can't test it, because I didn't own a elephone u pro anymore. And on mi9 it's not a problem.

**Comment by penn5** [comment] 2019-08-06 10:32
It **is** an issue on mi9. I own one. On CAF ROMs it works, but not in
aosp.

**Comment by phhusson** [comment] 2019-08-06 21:47
v117 has been released with the fix.

Please validate, so I can close that bug \o/

**Comment by penn5** [comment] 2019-08-07 11:09
Confirmed on dipper 117

**Comment by penn5** [comment] 2019-08-16 16:59
@phhusson i think it can be closed

**Closed** 2019-08-16 17:19 UTC
Labels: bounty

**Comment by rlzaleski** [comment] 2019-08-17 18:38
So what Build are @phhusson  and @penn5  using?  I'm running the ArrowOS build from Jul 12 https://sourceforge.net/projects/arrow-os/files/arrow-9.x/GSI/ on a Xiaomi MI 9, and when I add the routes to the XML and reboot I still don't get it to switch to Bluetooth.

A2DP does work through Pandora and such.

**Comment by penn5** [comment] 2019-08-17 20:30
All I can say. Is, #worksfineoverhere

**Comment by rlzaleski** [comment] 2019-08-17 23:31
Never said that at work ever ;-p
