### ISSUE TITLE
MTK XIAOMI REDMI 6A

### ISSUE THREAD

**Issue by DeeSh1** [phhusson/treble_experimentations#427] opened 2019-03-08 14:32 UTC
doesn't work outcoming calls on Xiaomi Redmi 6A

**Comment by DeeSh1** [comment] 2019-03-08 14:32
in AOSP 8 and 9

**Comment by abhilariya** [comment] 2019-03-09 04:34
Please delete this issue, i already posted it

**Comment by kzull** [comment] 2019-03-09 15:32
> Please delete this issue, i already posted it

HI,
Is this issue fixed ?

**Comment by abhilariya** [comment] 2019-03-09 15:35
> > Please delete this issue, i already posted it
> 
> HI,
> Is this issue fixed ?

No, I'm waiting for phh.

**Comment by kzull** [comment] 2019-03-09 15:59
> > > Please delete this issue, i already posted it
> > 
> > 
> > HI,
> > Is this issue fixed ?
> 
> No, I'm waiting for phh.

Thanks by reply

**Comment by phhusson** [comment] 2019-03-11 21:13
Dupe of #423

**Closed by phhusson** 2019-03-11 21:13 UTC
