### ISSUE TITLE
[Redmi Note 6 Pro] Bugs

### ISSUE THREAD

**Issue by RedmiNote6P** [phhusson/treble_experimentations#298] opened 2018-11-22 13:46 UTC
Bugs I found:
1. Auto brightness is not working. Screen flickering on brightness value changed.
2. Sometimes LED on the notch for notification is on all the time after reboot.
3. Screen flickering when wake up the phone.
4. Notch doesn't work properly.

**Comment by phhusson** [comment] 2018-11-22 13:51
You have five different sentences, so it should be five different issues, not one.

Good thing is, second half of 1. is the same bug as 3.

I recreated them:
https://github.com/phhusson/treble_experimentations/issues/299
https://github.com/phhusson/treble_experimentations/issues/300 I merged 1a and 4

2. is duplicate of https://github.com/phhusson/device_phh_treble/pull/49 I believe, please confirm.
If so, please add a comment to that issue mentioning your device.

**Closed by phhusson** 2018-11-22 13:51 UTC
