### ISSUE TITLE
Requires password to start android

### ISSUE THREAD

**Issue by jmmousee** [phhusson/treble_experimentations#346] opened 2018-12-24 18:08 UTC

**Comment by jmmousee** [comment] 2018-12-24 18:09
moto e5 plus

**Comment by peaktogoo** [comment] 2019-01-05 12:08
How do you even considered this as a bug report?

**Comment by penn5** [comment] 2019-01-27 09:19
@phhusson uh, close this to remove clutter i think

**Comment by penn5** [comment] 2019-01-27 09:19
> How did you even considered this as a bug report?

Its not a bug report even, there is no bug. His device just has FDE

**Closed** 2019-05-20 21:47 UTC
