### ISSUE TITLE
AOSP Q v204 no headset audio

### ISSUE THREAD

**Issue by joske** [phhusson/treble_experimentations#896] opened 2019-11-12 20:29 UTC
Op7T, when I connect headset via USB c dongle, audio still comes out of speakers, not headset.

**Comment by phhusson** [comment] 2019-11-12 20:35
Is it a passive or active dongle?

I'm guessing passive, there is a known Qualcomm issue: https://github.com/phhusson/treble_experimentations/issues/855

You can try to copy the policy attached in "fixed_policy.zip" in the second message to `/vendor/etc/audio_policy_configuration.xml`, and see if it fixes your issue

**Comment by joske** [comment] 2019-11-12 20:47
in the OS: 
OnePlus7T:/ # mount -o remount,rw /vendor
'/dev/block/dm-6' is read-only

And we don't have a working TWRP...

**Comment by joske** [comment] 2019-11-12 20:50
BTW, this does work on OOS 10.0.5 of course (using same vendor partition).

**Comment by phhusson** [comment] 2019-11-12 21:07
try `adb root` then `adb remount`

**Comment by joske** [comment] 2019-11-12 21:16
jos@xps13:~/Downloads/Android/OP7T$ adb root
* daemon not running; starting now at tcp:5037
* daemon started successfully
adbd cannot run as root in production builds

**Comment by phhusson** [comment] 2019-11-12 21:26
K, I guess you're not using my GSI as well, perhaps you have magisk
interfering?
Did you flash vbmeta with `fastboot --disable-verification --disable-verity
flash vbmeta vbmeta.img` ? (or google's vbmeta)

That should disable dm-verity on /vendor, and `mount -o remount,rw /vendor`
should work after that

Le mar. 12 nov. 2019 à 22:16, Jos Dehaes <notifications@github.com> a
écrit :

**Comment by joske** [comment] 2019-11-12 21:29
yes, magisk hide got in the way. Got the file in place, but now bluetooth is constantly crashing and wifi doesn't turn on, device unusable.

**Comment by joske** [comment] 2019-11-12 21:31
`11-12 22:30:37.035  1160  1160 E /vendor/bin/sscrpcd: vendor/qcom/proprietary/sensors-see/sscrpcd/src/sscrpcd.cpp:42:adsp daemon will restart after 25ms...
11-12 22:30:37.036   878   878 I /vendor/bin/sscrpcd: remote_handle_open: Successfully opened handle 0x64 for '":;./\createstaticpd:sensorspd on domain 2
11-12 22:30:37.036   878   878 E /vendor/bin/sscrpcd: Error 0xffffffff: apps_dev_init failed for domain 2, errno Transport endpoint is not connected
11-12 22:30:37.036   878   878 E /vendor/bin/sscrpcd: Error 0xffffffff: open_dev (-1) failed for domain 2
11-12 22:30:37.036   878   878 E /vendor/bin/sscrpcd: vendor/qcom/proprietary/sensors-see/sscrpcd/src/sscrpcd.cpp:42:adsp daemon will restart after 25ms...
11-12 22:30:37.049  1353  1353 I /vendor/bin/adsprpcd: remote_handle_open: Successfully opened handle 0x5d for '":;./\createstaticpd:audiopd on domain 0
11-12 22:30:37.050  1353  1353 E /vendor/bin/adsprpcd: Error 0xffffffff: apps_dev_init failed for domain 0, errno Transport endpoint is not connected
11-12 22:30:37.050  1353  1353 E /vendor/bin/adsprpcd: Error 0xffffffff: open_dev (-1) failed for domain 0
11-12 22:30:37.050  1353  1353 E /vendor/bin/adsprpcd: vendor/qcom/proprietary/commonsys-intf/adsprpc/src/adsprpcd.c:48:adsp daemon will restart after 25ms...
`

**Comment by phhusson** [comment] 2019-11-12 21:35
How did you uninstall magisk? Usually such issues are because you flashed
wrong version boot.img compared to vendor.img version

Anyway, I think you can flash back magisk, you should be able to remount
/vendor even with magisk once you have vbmeta

Le mar. 12 nov. 2019 à 22:29, Jos Dehaes <notifications@github.com> a
écrit :

**Comment by joske** [comment] 2019-11-12 21:38
I only disabled magisk hide, then I could remount. But even placing the backup file back didn't solve the bluetooth issue, reflashed the vendor partition and now fine again (well same as before, no audio from headphones).

**Comment by phhusson** [comment] 2019-11-12 21:45
Well now you have rw /vendor? you can push audio policy?

**Comment by joske** [comment] 2019-11-12 21:51
I could but as already stated above, that completely breaks the system.

**Comment by phhusson** [comment] 2019-11-12 22:48
Changing audio policy kills bluetooth and wifi, that's what you're saying?

**Comment by joske** [comment] 2019-11-13 06:01
Yes. Will diff the files later today.

**Comment by joske** [comment] 2019-11-13 09:01
Indeed the files are very similar with only difference the wired stuff. Maybe I did something wrong yesterday evening (tired). Will try again. Still don't understand why it works in OOS with exact same vendor file?

**Comment by joske** [comment] 2019-11-13 09:10
Same problem. Maybe there is some kind of tamper check/hash on the file? Logcat attached. Even stranger is that replacing the file with original is not enough to fix. Have to flash vendor partition back. [audio.logcat.txt](https://github.com/phhusson/treble_experimentations/files/3840273/audio.logcat.txt)

**Comment by joske** [comment] 2019-11-13 10:25
Also tried to mount the vendor image in linux, but that also fails with a strange error:
`EXT4-fs (loop13): couldn't mount as ext2 due to feature incompatibilities`
So no way to update the file in /vendor ...

**Comment by joske** [comment] 2019-11-13 10:32
[this could be the problem](https://android.googlesource.com/platform/system/core/+/a9a3b73163fda5abf237cc0f0cee97ff33e6254d/fs_mgr/README.overlayfs.md)

**Comment by natinusala** [comment] 2019-12-05 10:46
I was able to update the file in vendor (on an eng build, mind you) on my OnePlus 7 and I confirm it fixes the issue

**Comment by phhusson** [comment] 2019-12-05 20:43
Thanks

Mark as duplicate of #855

**Closed by phhusson** 2019-12-05 20:43 UTC
