### ISSUE TITLE
Loop Video in Realme 3

### ISSUE THREAD

**Issue by 01soni247** [phhusson/treble_experimentations#964] opened 2019-12-04 12:15 UTC
Loop Vidio In Realme 3, usually occurs in social media applications such as Wa, Fb, Telegram

**Comment by phhusson** [comment] 2019-12-04 12:22
That's a mediatek device correct?

**Comment by 01soni247** [comment] 2019-12-04 12:26
Yes, more precisely Mediatek P60

**Comment by 01soni247** [comment] 2019-12-04 12:29
I almost forgot, and also the fingerprint didn't work

**Comment by 01soni247** [comment] 2019-12-04 12:39
And I'm us (realme user 3), which we use Arm 64 A / B

**Comment by phhusson** [comment] 2019-12-04 12:44
Fingerprint is another issue, so open another issue.
The video issue is known, but I haven't got much clue about it.

**Comment by 01soni247** [comment] 2019-12-04 13:04
Ok, hopefully in the future it can be fixed

**Comment by phhusson** [comment] 2019-12-15 23:12
Duplicate of #1002

**Closed by phhusson** 2019-12-15 23:12 UTC
