### ISSUE TITLE
ussd doen not work on MTK

### ISSUE THREAD

**Issue by Anatoly33** [phhusson/treble_experimentations#273] opened 2018-10-31 09:09 UTC
ussd does not work on MTK soc's (mt6750 Homtom S99, mt6739 Vernee T3 Pro).
[t3pro_log.txt](https://github.com/phhusson/treble_experimentations/files/2533519/t3pro_log.txt)
[t3pro_radio_log.txt](https://github.com/phhusson/treble_experimentations/files/2533520/t3pro_radio_log.txt)
RilOpProxy: [getOpUnsolResponseInfo] dlopen failed in libmtk-rilop.so: (null)
This error after send ussd on MTK
This lib missing in vendor, also missing in /system/lib
ussd does not work

**Comment by Skyrimus** [comment] 2018-11-02 05:47
Phhusson knows it

**Comment by phhusson** [comment] 2019-12-16 19:36
Duplicate of #196

**Closed by phhusson** 2019-12-16 19:36 UTC
