### ISSUE TITLE
Asus Zenfone 5 (ZE620KL) Call Audio Problem

### ISSUE THREAD

**Issue by emincangencer** [phhusson/treble_experimentations#950] opened 2019-11-26 08:14 UTC
This doesn't happen with normal call. But apps like Whatsapp, Telegram, Bip calls have problems. The sound is completely blank. No white noise. I can't hear them and they can't hear me.
These are the dmesg and logcat:
[9stockbip.txt](https://github.com/phhusson/treble_experimentations/files/3890671/9stockbip.txt)
[9stockdmesg.txt](https://github.com/phhusson/treble_experimentations/files/3890672/9stockdmesg.txt)
[10phhbip.txt](https://github.com/phhusson/treble_experimentations/files/3890673/10phhbip.txt)
[10phhdmesg.txt](https://github.com/phhusson/treble_experimentations/files/3890674/10phhdmesg.txt)
If you need anything else @phhusson ask me and I will try to provide it to you. Thanks.

**Comment by phhusson** [comment] 2019-11-26 08:23
Duplicate of #839

**Comment by emincangencer** [comment] 2019-11-26 16:30
> Duplicate of #839

That thread is closed to. Does hat means you are working on fixing it?

**Comment by phhusson** [comment] 2019-11-26 17:38
Uh I see it open

Le mar. 26 nov. 2019 à 17:30, emincangencer <notifications@github.com> a
écrit :

**Closed** 2019-12-19 12:14 UTC
