### ISSUE TITLE
Bootloop payton

### ISSUE THREAD

**Issue by YukkiZx** [phhusson/treble_experimentations#1514] opened 2020-10-03 20:20 UTC
Logcat:--------- beginning of kernel
07-05 10:00:30.874     0     0 W [   11.246955,1] init: DM_DEV_STATUS failed for vroot: No such device or address
07-05 10:00:30.874     0     0 W [   11.247610,1] init: DM_DEV_STATUS failed for system: No such device or address
07-05 10:00:30.874     0     0 W [   11.247625,1] init: DM_DEV_STATUS failed for vroot: No such device or address
07-05 10:00:30.874     0     0 W [   11.248273,1] init: DM_DEV_STATUS failed for system: No such device or address
07-05 10:00:30.874     0     0 W [   11.248287,1] init: DM_DEV_STATUS failed for vroot: No such device or address
07-05 10:00:30.874     0     0 W [   11.248941,1] init: DM_DEV_STATUS failed for system: No such device or address
07-05 10:00:30.874     0     0 W [   11.248956,1] init: DM_DEV_STATUS failed for vroot: No such device or address
07-05 10:00:30.874     0     0 W [   11.249610,1] init: DM_DEV_STATUS failed for system: No such device or address
07-05 10:00:30.874     0     0 W [   11.249624,1] init: DM_DEV_STATUS failed for vroot: No such device or address
07-05 10:00:30.877     0     0 W [   11.250314,1] init: DM_DEV_STATUS failed for system: No such device or address
07-05 10:00:30.877     0     0 W [   11.250329,1] init: DM_DEV_STATUS failed for vroot: No such device or address
07-05 10:00:30.877     0     0 W [   11.250979,1] init: DM_DEV_STATUS failed for system: No such device or address
07-05 10:00:30.877     0     0 W [   11.250997,1] init: DM_DEV_STATUS failed for vroot: No such device or address
07-05 10:00:30.877     0     0 W [   11.251649,1] init: DM_DEV_STATUS failed for system: No such device or address
07-05 10:00:30.877     0     0 W [   11.251664,1] init: DM_DEV_STATUS failed for vroot: No such device or address
07-05 10:00:32.442     0     0 I [   12.817969,1] init: Command 'setprop ro.vndk.version ${persist.sys.vndk}' action=post-fs (/system/etc/init/vndk.rc:5) took 0ms and failed: property 'persist.sys.vndk' doesn't exist while expanding '${persist.sys.vndk}'
07-05 10:00:32.442     0     0 I [   12.818143,1] init: processing action (late-fs) from (/system/etc/init/hw/init.rc:531)
07-05 10:00:32.444     0     0 I [   12.819539,1] init: starting service 'system_suspend'...
07-05 10:00:32.447     0     0 I [   12.822066,1] init: starting service 'vendor.boot-hal-1-0'...
07-05 10:00:32.450     0     0 I [   12.824554,1] init: starting service 'vendor.keymaster-3-0'...
07-05 10:00:32.454     0     0 I [   12.827057,1] init: processing action (late-fs) from (/vendor/etc/init/hw/init.qcom.rc:101)
07-05 10:00:32.454     0     0 I [   12.827729,1] init: starting service 'surfaceflinger'...
07-05 10:00:32.454     0     0 I [   12.828200,1] init: Could not create socket 'pdx/system/vr/display/client': Failed to bind socket 'pdx/system/vr/display/client': No such file or directory
07-05 10:00:32.454     0     0 I [   12.828456,1] init: Could not create socket 'pdx/system/vr/display/manager': Failed to bind socket 'pdx/system/vr/display/manager': No such file or directory
07-05 10:00:32.454     0     0 I [   12.828720,1] init: Could not create socket 'pdx/system/vr/display/vsync': Failed to bind socket 'pdx/system/vr/display/vsync': No such file or directory
07-05 10:00:32.457     0     0 I [   12.831669,1] init: starting service 'bootanim'...
07-05 10:00:32.460     0     0 I [   12.835167,1] init: starting service 'vendor.configstore-hal'...
07-05 10:00:32.466     0     0 I [   12.838493,1] init: starting service 'vendor.gralloc-2-0'...
07-05 10:00:32.470     0     0 I [   12.843476,1] init: start_waiting_for_property("hwservicemanager.ready", "true"): already set
07-05 10:00:32.484     0     0 I [   12.857001,1] init: [libfs_mgr]superblock s_max_mnt_count:65535,/dev/block/bootdevice/by-name/userdata
07-05 10:00:32.494     0     0 W         : [   12.867904,1] EXT4-fs (mmcblk0p67): Ignoring removed nomblk_io_submit option
07-05 10:00:32.594     0     0 I         : [   12.969426,6] EXT4-fs (mmcblk0p67): mounted filesystem with ordered data mode. Opts: errors=remount-ro,nomblk_io_submit
07-05 10:00:32.594     0     0 I [   12.969868,6] init: [libfs_mgr]check_fs(): mount(/dev/block/bootdevice/by-name/userdata,/data,ext4)=0: Success
07-05 10:00:32.600     0     0 I [   12.975373,6] init: [libfs_mgr]check_fs(): unmount(/data) succeeded
07-05 10:00:32.600     0     0 I [   12.975580,6] init: [libfs_mgr]Running /system/bin/e2fsck on /dev/block/mmcblk0p67
07-05 10:00:32.617     0     0 I [   12.990153,5] e2fsck: e2fsck 1.45.4 (23-Sep-2019)
07-05 10:00:32.650     0     0 I [   13.024641,5] e2fsck: /dev/block/bootdevice/by-name/userdata: clean, 1404/3178496 files, 281162/12699643 blocks
07-05 10:00:32.654     0     0 I [   13.029292,6] init: [libfs_mgr]superblock s_max_mnt_count:65535,/dev/block/bootdevice/by-name/userdata
07-05 10:00:32.659     0     0 I         : [   13.035261,7] EXT4-fs (mmcblk0p67): barriers disabled
07-05 10:00:32.664     0     0 I         : [   13.039648,7] EXT4-fs (mmcblk0p67): mounted filesystem with ordered data mode. Opts: nobarrier,discard,data=ordered,noauto_da_alloc
07-05 10:00:32.664     0     0 I [   13.039988,7] init: [libfs_mgr]__mount(source=/dev/block/bootdevice/by-name/userdata,target=/data,type=ext4)=0: Success
07-05 10:00:32.669     0     0 I [   13.040866,7] init: [libfs_mgr]/data is file encrypted
07-05 10:00:32.680     0     0 I [   13.055385,2] init: [libfs_mgr]superblock s_max_mnt_count:65535,/dev/block/by-name/system_a
07-05 10:00:32.680     0     0 I [   13.055748,2] init: [libfs_mgr]check_fs(): mount(/dev/block/by-name/system_a,/mnt/scratch,ext4)=-1: Permission denied
07-05 10:00:32.680     0     0 I [   13.055841,2] init: [libfs_mgr]Running /system/bin/e2fsck on /dev/block/mmcblk0p65
07-05 10:00:32.694     0     0 I [   13.069658,7] e2fsck: e2fsck 1.45.4 (23-Sep-2019)
07-05 10:00:32.697     0     0 I [   13.072542,7] e2fsck: /system/bin/e2fsck: Operation not permitted while trying to open /dev/block/by-name/system_a
07-05 10:00:32.697     0     0 I [   13.072574,7] e2fsck: You must have r/w access to the filesystem or be root
07-05 10:00:32.700     0     0 I [   13.073647,7] e2fsck: e2fsck terminated by exit(8)
07-05 10:00:32.700     0     0 I         : [   13.073647,7]
07-05 10:00:32.700     0     0 I [   13.074012,7] init: [libfs_mgr]e2fsck returned status 0x800
07-05 10:00:32.700     0     0 E [   13.074565,7] init: Unable to set property 'ro.boottime.init.fsck.scratch' from uid:0 gid:0 pid:1: Read-only property was already set
07-05 10:00:32.704     0     0 I         : [   13.079470,4] EXT4-fs (mmcblk0p65): mounted filesystem with ordered data mode. Opts:
07-05 10:00:32.704     0     0 I [   13.079685,4] init: [libfs_mgr]__mount(source=/dev/block/by-name/system_a,target=/mnt/scratch,type=ext4)=0: Success
07-05 10:00:32.704     0     0 E [   13.080160,7] init: Unable to set property 'ro.boottime.init.mount.scratch' from uid:0 gid:0 pid:1: Read-only property was already set
07-05 10:00:32.708     0     0 I [   13.081659,4] init: [libfs_mgr]umount(/mnt/scratch)
07-05 10:00:32.710     0     0 I [   13.084200,4] init: Keyring created with id 168550153 in process 1
07-05 10:00:32.710     0     0 I [   13.084754,4] init: Command 'mount_all /vendor/etc/fstab.qcom --late' action=late-fs (/vendor/etc/init/hw/init.qcom.rc:116) took 241ms and succeeded
07-05 10:00:32.710     0     0 W [   13.085232,4] init: DM_DEV_STATUS failed for system: No such device or address
07-05 10:00:32.710     0     0 W [   13.085253,4] init: DM_DEV_STATUS failed for vroot: No such device or address
07-05 10:00:32.710     0     0 W [   13.086667,4] init: DM_DEV_STATUS failed for system: No such device or address

**Comment by phhusson** [comment] 2020-10-03 20:27
I see no error in there
Please post full log either as an attachment or to something like pastebin.com

Also, what's your device?
Which GSI are you trying to boot?

**Comment by YukkiZx** [comment] 2020-10-03 20:57
my cell phone is moto x4
I'm using the last Roar and I'm having a bootloop. I'll send the link to the full log.

**Comment by YukkiZx** [comment] 2020-10-03 21:04
https://del.dog/crirfengeg.txt

**Comment by YukkiZx** [comment] 2020-10-03 21:06
https://drive.google.com/file/d/104vxHmnQ6-r2SAbTSdNy3gXCvYUgFFOV/view?usp=drivesdk

**Comment by phhusson** [comment] 2020-10-03 21:25
I guess that's not OEM-provided vendor since it was released with nougat?

**Comment by YukkiZx** [comment] 2020-10-03 21:26
Yes this is not the vendor oem I used Lineage os 17.1 as a vendor

**Comment by phhusson** [comment] 2020-10-04 08:24
I would say the issue is that you vendor declares android.hardware.weaver@1.0::IWeaver but doesn't have it

**Comment by YukkiZx** [comment] 2020-10-07 01:00
Thanks

**Closed** 2020-10-08 20:07 UTC
