### ISSUE TITLE
A505x Fingerprint

### ISSUE THREAD

**Issue by Suzakun14** [phhusson/treble_experimentations#828] opened 2019-11-02 02:32 UTC
So far nothing for this problem?

**Comment by phhusson** [comment] 2019-11-02 09:47
What problem?
What device?
 Which gsi version?

**Comment by mateoquintero** [comment] 2019-11-02 14:54
> What problem?
> What device?
> Which gsi version?

Fingerprint on display is not working on samsung A50 on any gsi version.

**Comment by phhusson** [comment] 2019-11-02 14:56
Duplicate of #490

**Closed by phhusson** 2019-11-02 14:56 UTC
