### ISSUE TITLE
Samsung a30

### ISSUE THREAD

**Issue by realartin** [phhusson/treble_experimentations#1731] opened 2021-02-23 09:32 UTC
Hi i dl all version of your android 11 arm 64 ab
And i flashed on my samsung a305f
It is amazing fast and responsive and i love it thank you
The main issue is i haved randomly reboot s
I try to flash other kernels but problem is still / steel here
I use another build that they are using your build as the main build like havoc os but the problem ( rendom reboot ) is here
Please fix it
Tnx a lot.

**Comment by phhusson** [comment] 2021-02-23 09:33
Duplicate of #1730 just edit your bug.

**Closed** 2021-02-23 09:33 UTC
