### ISSUE TITLE
htc u11+ cannot boot 

### ISSUE THREAD

**Issue by jinbolx** [phhusson/treble_experimentations#147] opened 2018-08-22 12:12 UTC
[AOSP 9.0] [EXPERIMENTAL] [2018-08-21] Phh-Treble  cannot boot ,then boot into bl mode .

AOSP 8.1] [2018-08-16] Phh-Treble        this version can boot

**Comment by phhusson** [comment] 2018-08-22 12:13
Get me /sys/fs/pstore and/or /proc/last_kmsg

**Comment by jinbolx** [comment] 2018-08-22 12:44
how to get it?

**Comment by yefonme** [comment] 2018-09-11 02:11
> Get me /sys/fs/pstore and/or /proc/last_kmsg
I tried on my U11+,there is nothing in /sys/fs/pstore, and the /proc/last_kmsg file does not exist.

**Comment by phhusson** [comment] 2019-05-18 19:51
Could be a dupe of https://github.com/phhusson/treble_experimentations/issues/309, or not (I'm guessing not)

@xymopen sorry I'm (very) late, your link is dead.

Could someone get me logs again?

**Comment by xymopen** [comment] 2019-05-19 06:45
Sorry my U11+ was (physical) damaged and I cannot grab another logcat.

**Closed** 2019-12-16 20:38 UTC
