### ISSUE TITLE
HTC U12+ on gapps su v105

### ISSUE THREAD

**Issue by jeanrivera** [phhusson/treble_experimentations#209] opened 2018-09-23 01:43 UTC
it gives me the no simcard error and it bootloops to an unresposive blackscreen over and over I have to skip setup wizard because of this issue 
[logcat.txt](https://github.com/phhusson/treble_experimentations/files/2408324/logcat.txt)

here is another log while booting 
[mylogfile.txt](https://github.com/phhusson/treble_experimentations/files/2408327/mylogfile.txt)

couriosly turning off wifi stops the loop and it lets me browse around the OS and open the apps

**Comment by phhusson** [comment] 2018-09-24 05:59
Most likely dupe of #207

**Closed by phhusson** 2018-09-24 05:59 UTC
