### ISSUE TITLE
[AOSP 9.0][Mi 8 Pro (Mi8UD/equuleus)]: bluetooth audio problem by calling

### ISSUE THREAD

**Issue by zhifuyu** [phhusson/treble_experimentations#342] opened 2018-12-20 20:46 UTC
Bluetooth connection to headset, when I accept a call or call someone, they can hear my voice, but I cannot hear their.

**Comment by phhusson** [comment] 2019-05-20 21:37
Dupe of https://github.com/phhusson/treble_experimentations/issues/374

**Closed by phhusson** 2019-05-20 21:37 UTC
