### ISSUE TITLE
Introduce a variant "LineageOS for microG"? 

### ISSUE THREAD

**Issue by thinkpadder1** [phhusson/treble_experimentations#103] opened 2018-07-01 16:20 UTC
Would it be possible to introduce **LineageOS for microG** [https://lineage.microg.org/](https://lineage.microg.org/) as a new build variant?

I can help develop this, but I wanted to see if people were open to the idea before I dived in.

It's the same exact thing as the regular LineageOS, but some extras
- signature spoofing
- microG and F-droid are built in and supported by the MicroG team https://microg.org/
- Upstreamed weekly OTA updates from Lineage as well

Having this microG variant will allow people to use open source software but still use apps that heavily rely on some Google APIs that make some apps impossible to use (won't launch, etc) including any apps (banking, specialized navigation, etc)
- that use the Google Maps Android API, drastically speeding up geolocation without having google track your every step with Unified Network Location Provider (provides alternative providers + offline providers). 
- the Services Framework Proxy which lets you use Google Cloud Messaging for apps with notifications if necessary (disabled by default)
- and anything that uses Google Play Services API (which so many modern apps do and they refuse to launch otherwise)
- And more which you can check out at https://microg.org/

And if this is a go, any tips would be helpful to get started. My naive view is that I am not expecting it to be different from the LineageOS variant that already exists in this project... so it might be possible to straight up copy/paste what this repo has for Lineage and change a few variables.

**Comment by phhusson** [comment] 2018-07-01 20:15
Yes that's something I'd like to have, though as part of my "floss" build, not as a new variant (And not just Lineage, but all ROMs I support, currently AOSP+Lineage+RR)
(Well I don't build floss for lineage, at the moment, but that's a one liner).
Now the problem is that I don't want to push that in my tree as other patches, so that I don't force this patch to everyone.

Looks like they have a patch-over-stock build system just like me, so the integration won't be trivial.
It wouldn't be too hard to make change my build scripts to include per-variant patches, the problem is that "LineageOS for microG" seem to do much more than just applying an extra patch, and it's not totally easy to know what they do.

From what I gather, you additionally need to:
- include microG apks ( https://github.com/lineageos4microg/android_prebuilts_prebuiltapks )
You just need to add it to https://github.com/phhusson/treble_manifest/blob/master/foss.xml
The problem with this repo is that it is not guarded and will conflict with opengapps or android go gapps when building their respective variant. You can look at https://github.com/phhusson/gapps-go/commit/f6abbf01537a9a461f28d30db29e0f46cbc9fa27 for how I do that on Android Go gapps
One way which wouldn't require to change their repo is to make it into a sub-folder and have the upper folder guard the lower folder, something like:
vendor/foss/ # Our own repo
vendor/foss/Android.mk # Includes a guard to include the apks only when needed
vendor/foss/foss.mk # Declares the flag needed to pass the guard
vendor/foss/android_prebuilts_prebuiltapks # Actual lineageos4microg's repo
- Specify which apps you want to add (     -e "CUSTOM_PACKAGES=GmsCore GsfProxy FakeStore MozillaNlpBackend NominatimNlpBackend com.google.android.maps.jar FDroid FDroidPrivilegedExtension " \ ), and add it to https://github.com/phhusson/vendor_foss/blob/master/foss.mk
- Include the overlay (cf https://github.com/lineageos4microg/docker-lineage-cicd/blob/master/src/signature_spoofing_patches/frameworks_base_config.xml )
- https://github.com/evs-ch/android_packages_apps_GmsCore/commit/611cd82a55665c213ab7491c021418170054d69d additionally has a change to config_locationProviderPackageNames I don't know if that's relevant
- Ensure we use restricted version, not the dangerous one ( https://github.com/lineageos4microg/docker-lineage-cicd/blob/master/src/build.sh#L180 )

That's all I can see for the moment, but I'm guessing other problems will arise...

**Comment by thinkpadder1** [comment] 2018-07-04 18:34
I've tried and given up. Decided to stick with stock AOSP and that I'm better off not touching the Google related apps at all. I have updated one of the device wikis as well.

Thank you for helping. I'll close this issue, but feel free to reopen it.

**Comment by phhusson** [comment] 2019-05-18 17:44
K, I'm closing this because I no longer maintain Lineage GSI, and some people started building their own AOSP with microg ( https://forum.xda-developers.com/project-treble/trebleenabled-device-development/arm64aosp-9-0-0r21-microg-ufofficial-t3878115 )

**Closed by phhusson** 2019-05-18 17:44 UTC
