### ISSUE TITLE
[Moto G6 Plus] A2DP connects but doesn't play

### ISSUE THREAD

**Issue by ghost** [phhusson/treble_experimentations#126] opened 2018-07-24 09:54 UTC
Bluetooth will connect to device but audio isn't playing. ROM is LineageOS but this also happens on Resurrection Remix.

**Comment by najjannaj** [comment] 2018-07-31 09:45
Same on Moto G6

**Comment by Jalohann** [comment] 2018-08-08 16:40
Same on Nokia 6.1.

**Comment by st-noigel** [comment] 2018-08-15 19:17
Same on Sharp s2 (SD630)

**Comment by m-rufflesmcghie** [comment] 2018-08-15 19:41
I had on Moto G5 treble Pedro built....Check Do Not Disturb settings for media this was the issue.
I can connect and play music but can't connect to Fitbit or TV

**Comment by myfreeweb** [comment] 2018-10-03 20:38
Looks like `/vendor/etc/audio/audio_policy_configuration.xml` is the problem, see #133, https://github.com/phhusson/device_phh_treble/pull/26

I renamed that file and Bluetooth audio started working. (Lineage 16, Xiaomi Mi A2)

**Comment by BugReporter2** [comment] 2019-05-05 06:48
@phhusson 

This is still a problem with the latest version, `AOSP 9.0 v112`.

[This method](https://github.com/phhusson/treble_experimentations/issues/184#issuecomment-427603178) successfully fixes this Bluetooth problem until the next reboot.

Could you investigate this? I'll happily give some logs and help to solve this.

**Comment by penn5** [comment] 2019-05-05 08:28
> @phhusson
> 
> This is still a problem with the latest version, `AOSP 9.0 v112`.
> 
> [This method](https://github.com/phhusson/treble_experimentations/issues/184#issuecomment-427603178) successfully fixes this Bluetooth problem until the next reboot.
> 
> Could you investigate this? I'll happily give some logs and help to solve this.

We need a list of affected devices (build fingerprint from vendor please), add them to the soundfx blacklist and we're done.

**Comment by BugReporter2** [comment] 2019-05-05 16:20
> We need a list of affected devices (build fingerprint from vendor please)

Can I help with this somehow?

**Comment by phhusson** [comment] 2019-05-05 17:42
K, I ignored this bug, because from the title, it looked like something complicated.

If you want answers, the title of the issue is one of the most important thing.

**Comment by phhusson** [comment] 2019-12-16 20:31
Disabling soundfx has been merged some time ago, so i guess i can close this issue

**Closed by phhusson** 2019-12-16 20:31 UTC
