### ISSUE TITLE
[S10/S10+/S10E] Non functional MTP

### ISSUE THREAD

**Issue by DrRambone** [phhusson/treble_experimentations#516] opened 2019-05-09 16:52 UTC
At least on S10e

**Comment by uvitor** [comment] 2019-05-09 18:17
S10+ not working as well, but adb do work.

**Comment by uvitor** [comment] 2019-05-10 01:06
I dont know if it helps but here is the logcat from the moment i plug usb to connect Phone---PC which results in non functional MTP but adb work  as intended.




05-09 21:57:15.308 W/Ringtone(5714): Neither local nor remote player available when applying playback properties
05-09 21:57:15.309 W/Ringtone(5714): Neither local nor remote playback available
05-09 21:57:15.318 I/GCoreUlr(7751): DispatchingService.updateActiveState+PowerModeReceiver: Ensuring that reporting is active for [account#-12#]
05-09 21:57:15.319 I/GCoreUlr(7751): Successfully accounts update
05-09 21:57:15.324 I/GCoreUlr(7751): Step counts collector feature is not enabled!
05-09 21:57:15.326 E/BluetoothAdapter(7751): Bluetooth binder is null
05-09 21:57:15.340 I/SystemUpdate(7713): [Installation,ReceiverIntentOperation] Received intent: Intent { act=android.intent.action.ACTION_POWER_CONNECTED flg=0x4000010 cmp=com.google.android.gms/.chimera.GmsIntentOperationService (has extras) }.
05-09 21:57:15.348 I/android.hardware.wifi@1.0-service(5258): Successfully getLinkLayerStats.
05-09 21:57:15.349 E/BluetoothAdapter(5545): Bluetooth binder is null
05-09 21:57:15.350 I/SystemUpdate(7713): [Execution,InstallationEventIntentOperation] Handling event of type 9.
05-09 21:57:15.355 I/SystemUpdate(7713): [Execution,InstallationIntentOperation] Received intent: Intent { act=com.google.android.gms.update.INSTALL_UPDATE cat=[targeted_intent_op_prefix:.update.execution.InstallationIntentOperation] cmp=com.google.android.gms/.chimera.GmsIntentOperationService }.
05-09 21:57:15.363 I/SystemUpdate(7713): [Execution,ExecutionManager] Action finished-execution executed for 0.00 seconds.
05-09 21:57:15.390 D/UsbDeviceManager(5545): push notification:Charging this device via USB
05-09 21:57:15.436 I/adbd    (6151): closing functionfs transport
05-09 21:57:15.510 W/kworker/4:0(9587): type=1400 audit(0.0:28685): avc: denied { open } for path="/sys/devices/virtual/sec/sec_key/hall_detect" dev="sysfs" ino=50755 scontext=u:r:kernel:s0 tcontext=u:object_r:sysfs:s0 tclass=file permissive=0
05-09 21:57:15.532 I/adbd    (6151): initializing functionfs
05-09 21:57:15.534 I/adbd    (6151): functionfs successfully initialized
05-09 21:57:15.534 I/adbd    (6151): registering usb transport
05-09 21:57:15.661 D/bauth_FPBAuthService(5415): pcf : 0x1012, 0 ,3 ,0 ,0 ,0 ,0, 2.0.8.4
05-09 21:57:15.661 D/bauth_FPBAuthService(5415): thread id : 3, preenroll_flag : 0, nd cnt : 0, cso : 0, et : 0
05-09 21:57:15.661 D/bauth_FPBAuthService(5415): FPBAuthService, 10018
05-09 21:57:15.896 I/adbd    (6162): initializing functionfs
05-09 21:57:15.896 I/adbd    (6162): opening control endpoint /dev/usb-ffs/adb/ep0
05-09 21:57:16.662 D/bauth_FPBAuthService(5415): pcf : 0x1012, 0 ,3 ,0 ,0 ,0 ,0, 2.0.8.4
05-09 21:57:16.662 D/bauth_FPBAuthService(5415): thread id : 3, preenroll_flag : 0, nd cnt : 0, cso : 0, et : 0
05-09 21:57:16.662 D/bauth_FPBAuthService(5415): FPBAuthService, 10018
05-09 21:57:16.897 I/adbd    (6162): initializing functionfs
05-09 21:57:16.897 I/adbd    (6162): opening control endpoint /dev/usb-ffs/adb/ep0
05-09 21:57:17.526 W/kworker/4:0(9587): type=1400 audit(0.0:28686): avc: denied { open } for path="/sys/devices/virtual/sec/sec_key/hall_detect" dev="sysfs" ino=50755 scontext=u:r:kernel:s0 tcontext=u:object_r:sysfs:s0 tclass=file permissive=0
05-09 21:57:17.663 D/bauth_FPBAuthService(5415): pcf : 0x1012, 0 ,3 ,0 ,0 ,0 ,0, 2.0.8.4
05-09 21:57:17.663 D/bauth_FPBAuthService(5415): thread id : 3, preenroll_flag : 0, nd cnt : 0, cso : 0, et : 0
05-09 21:57:17.663 D/bauth_FPBAuthService(5415): FPBAuthService, 10018
05-09 21:57:17.898 I/adbd    (6162): initializing functionfs
05-09 21:57:17.898 I/adbd    (6162): opening control endpoint /dev/usb-ffs/adb/ep0
05-09 21:57:18.664 D/bauth_FPBAuthService(5415): pcf : 0x1012, 0 ,3 ,0 ,0 ,0 ,0, 2.0.8.4
05-09 21:57:18.664 D/bauth_FPBAuthService(5415): thread id : 3, preenroll_flag : 0, nd cnt : 0, cso : 0, et : 0
05-09 21:57:18.664 D/bauth_FPBAuthService(5415): FPBAuthService, 10018
05-09 21:57:18.899 I/adbd    (6162): initializing functionfs
05-09 21:57:18.899 I/adbd    (6162): opening control endpoint /dev/usb-ffs/adb/ep0
05-09 21:57:19.542 W/kworker/4:0(9587): type=1400 audit(0.0:28687): avc: denied { open } for path="/sys/devices/virtual/sec/sec_key/hall_detect" dev="sysfs" ino=50755 scontext=u:r:kernel:s0 tcontext=u:object_r:sysfs:s0 tclass=file permissive=0
05-09 21:57:19.664 D/bauth_FPBAuthService(5415): pcf : 0x1012, 0 ,3 ,0 ,0 ,0 ,0, 2.0.8.4
05-09 21:57:19.664 D/bauth_FPBAuthService(5415): thread id : 3, preenroll_flag : 0, nd cnt : 0, cso : 0, et : 0
05-09 21:57:19.665 D/bauth_FPBAuthService(5415): FPBAuthService, 10018
05-09 21:57:19.900 I/adbd    (6162): initializing functionfs
05-09 21:57:19.900 I/adbd    (6162): opening control endpoint /dev/usb-ffs/adb/ep0
05-09 21:57:20.665 D/bauth_FPBAuthService(5415): pcf : 0x1012, 0 ,3 ,0 ,0 ,0 ,0, 2.0.8.4
05-09 21:57:20.665 D/bauth_FPBAuthService(5415): thread id : 3, preenroll_flag : 0, nd cnt : 0, cso : 0, et : 0
05-09 21:57:20.665 D/bauth_FPBAuthService(5415): FPBAuthService, 10018
05-09 21:57:20.901 I/adbd    (6162): initializing functionfs
05-09 21:57:20.901 I/adbd    (6162): opening control endpoint /dev/usb-ffs/adb/ep0
05-09 21:57:21.558 W/kworker/4:0(9587): type=1400 audit(0.0:28688): avc: denied { open } for path="/sys/devices/virtual/sec/sec_key/hall_detect" dev="sysfs" ino=50755 scontext=u:r:kernel:s0 tcontext=u:object_r:sysfs:s0 tclass=file permissive=0
05-09 21:57:21.665 D/bauth_FPBAuthService(5415): pcf : 0x1012, 0 ,3 ,0 ,0 ,0 ,0, 2.0.8.4
05-09 21:57:21.665 D/bauth_FPBAuthService(5415): thread id : 3, preenroll_flag : 0, nd cnt : 0, cso : 0, et : 0
05-09 21:57:21.666 D/bauth_FPBAuthService(5415): FPBAuthService, 10018
05-09 21:57:21.902 I/adbd    (6162): initializing functionfs
05-09 21:57:21.902 I/adbd    (6162): opening control endpoint /dev/usb-ffs/adb/ep0

**Comment by phhusson** [comment] 2019-05-21 07:53
Dupe of #225

**Closed by phhusson** 2019-05-21 07:53 UTC
