### ISSUE TITLE
Google Dialer warns calls might be broken

### ISSUE THREAD

**Issue by denondj87** [phhusson/treble_experimentations#883] opened 2019-11-11 19:01 UTC
Hi i have an s8 and i installed your rom android 10 v 203

I have an errore in dialer ,He says in english :  your device maybe not supported and the phone calls potentially didin't workss
See attached
![Screenshot_20191111-193433](https://user-images.githubusercontent.com/39927178/68613014-1a507800-04be-11ea-946d-60b9532efbab.png)

**Comment by phhusson** [comment] 2019-11-11 22:46
Duplicate of #866

**Closed** 2019-11-12 20:33 UTC
