### ISSUE TITLE
Adaptive brightness not working in Samsung Galaxy A10 

### ISSUE THREAD

**Issue by navabisamar** [phhusson/treble_experimentations#1470] opened 2020-09-08 17:06 UTC
Adaptive brightness isn't working in Samsung Galaxy A10. The device doesn't have a light sensor. In stock Oneui, the software uses front camera as light sensor to adjust brightness automatically.

**Comment by phhusson** [comment] 2020-09-08 17:11
Duplicate of https://github.com/phhusson/treble_experimentations/issues/1468

**Closed by phhusson** 2020-09-08 17:11 UTC
