### ISSUE TITLE
[AOSP 9.0] [Moto G6 Plus] Sim card not recognized

### ISSUE THREAD

**Issue by debugger2019** [phhusson/treble_experimentations#206] opened 2018-09-22 07:45 UTC
Version: AOSP 9.0 v105

Issue: Sim card isn't getting rezognized. Tried both sim slots and factory reset and multiple re-boots. WiFi works.

**Comment by codejoe87** [comment] 2018-09-22 10:05
I have Moto G6 Plus and I can confirm this too. Here is logcat:
https://ghostbin.com/paste/jzfxc

**Comment by jomo** [comment] 2019-01-05 00:59
Having the same issue on Moto G6 Plus with Lineage. It's a dual SIM device and neither seems to be recognized.

I disabled SELinux just to be sure it's not causing the issue.

Relevant log lines from startup with a SIM card inserted:

```logcat
D rmt_storage: open_gzfsg: b_radio=0, b_multisim=1
I OMXMaster: makeComponentInstance(OMX.google.gsm.decoder) in omx@1.0-service process
D TelephonyProvider: dbh.onOpen: ok, queried table=siminfo
D CarrierConfigLoader: mHandler: 12 phoneId: 0
D CarrierConfigLoader: update config for phoneId: 0 simState: ABSENT
D CarrierSvcBindHelper: update binding for phoneId: 0 simState: ABSENT
D SimSelectNotification: simstatus = ABSENT
D CarrierConfigLoader: update config for phoneId: 1 simState: ABSENT
D CarrierSvcBindHelper: update binding for phoneId: 1 simState: ABSENT
D CarrierConfigLoader: mHandler: 0 phoneId: 0
D CarrierSvcBindHelper: Rebinding if necessary for phoneId: 0
D SimSelectNotification: simstatus = ABSENT
D CarrierConfigLoader: mHandler: 0 phoneId: 1
D CarrierSvcBindHelper: Rebinding if necessary for phoneId: 1
I getprop : type=1400 audit(0.0:128): avc: denied { open } for uid=0 path="/dev/__properties__/u:object_r:uicc_prop:s0" dev="tmpfs" ino=6004 scontext=u:r:phhsu_daemon:s0 tcontext=u:object_r:uicc_prop:s0 tclass=file permissive=1
I getprop : type=1400 audit(0.0:129): avc: denied { getattr } for uid=0 path="/dev/__properties__/u:object_r:uicc_prop:s0" dev="tmpfs" ino=6004 scontext=u:r:phhsu_daemon:s0 tcontext=u:object_r:uicc_prop:s0 tclass=file permissive=1
D CarrierConfigLoader: update config for phoneId: 0 simState: ABSENT
D CarrierSvcBindHelper: update binding for phoneId: 0 simState: ABSENT
D CarrierConfigLoader: mHandler: 0 phoneId: 0
D CarrierConfigLoader: update config for phoneId: 1 simState: ABSENT
D CarrierSvcBindHelper: update binding for phoneId: 1 simState: ABSENT
D CarrierConfigLoader: mHandler: 0 phoneId: 1
D CarrierConfigLoader: mHandler: 13 phoneId: 0
D SimSelectNotification: simstatus = ABSENT
D SimSelectNotification: simstatus = ABSENT
```

There's zero log when removing or inserting a SIM card into either slot 1 or 2 afterwards.

**Comment by BugReporter2** [comment] 2019-05-05 06:41
This is fixed in the latest version(s). This issue can be closed.

**Closed** 2019-05-05 17:47 UTC
