### ISSUE TITLE
[Honor 8][AOSP 10 v206] SIM Card can't be recognized

### ISSUE THREAD

**Issue by k10876** [phhusson/treble_experimentations#985] opened 2019-12-07 13:41 UTC
com.android.phone often stops working.
I can't use mobile data even if SIM Card plugged in.
**Emergency Call Can't be used.**

**Comment by phhusson** [comment] 2019-12-08 22:35
I need logs:
`adb logcat -b all > log.txt`
Did you try both SIM slots?

**Comment by phhusson** [comment] 2019-12-08 22:36
#984 says that at least one SIM card slot works fine.

**Comment by phhusson** [comment] 2019-12-08 23:57
K, after further research, this is indeed a duplicate of #984 
So I'm closing this issue. #984 will be fixed in next Q release.

**Closed by phhusson** 2019-12-08 23:57 UTC

**Comment by k10876** [comment] 2019-12-09 11:56
Thanks a lot
