### ISSUE TITLE
HTC U12+ on floss su

### ISSUE THREAD

**Issue by jeanrivera** [phhusson/treble_experimentations#208] opened 2018-09-23 00:55 UTC
on this version I can barely open some apps, camera, file manager gallery none of them open and it gives me the same error process.media kepps stopping
[logcat.txt](https://github.com/phhusson/treble_experimentations/files/2408295/logcat.txt)

**Comment by phhusson** [comment] 2018-09-24 05:59
Most likely dupe of #207

**Closed by phhusson** 2018-09-24 05:59 UTC
