### ISSUE TITLE
[Huawei P20 PRO] - Fingerprints 

### ISSUE THREAD

**Issue by Edsol** [phhusson/treble_experimentations#134] opened 2018-08-05 07:56 UTC
When I configure the Fingerprints the sensor work fine and recognize the fingerprints but at the end get this error message and don't save anything. I think the problem is on save the informations?
![photo_2018-08-05_09-56-08](https://user-images.githubusercontent.com/19670024/43683900-d07b391c-9895-11e8-9a71-a32ab44d6724.jpg)
![photo_2018-08-05_09-52-05](https://user-images.githubusercontent.com/19670024/43683905-d327d044-9895-11e8-8db7-afe2b2b10f61.jpg)

**Comment by phhusson** [comment] 2018-08-05 07:58
Duplicate of #39

**Closed by phhusson** 2018-08-05 07:58 UTC
