### ISSUE TITLE
[Ulefone armor 6e] playback in app stuttering

### ISSUE THREAD

**Issue by fherenda1** [phhusson/treble_experimentations#1115] opened 2020-02-18 15:51 UTC
Videos in reddit app are stuttery, but when open in firefox they work fine. 
Not sure if it is because od the app or the system. Youtube app does not have the same issue fine. 
Otherwise system works great on this phone.

**Comment by phhusson** [comment] 2020-02-18 16:40
Duplicate of #1002 
See https://issuetracker.google.com/issues/148962635

**Closed by phhusson** 2020-02-18 16:40 UTC
