### ISSUE TITLE
The second SIM does not work on Huawei P20 Lite

### ISSUE THREAD

**Issue by Alkalainov** [phhusson/treble_experimentations#1063] opened 2020-01-10 14:18 UTC
The second sim does not work on the Huawei P20 Lite phone. It does not appear in the status bar and there is no item in the settings. Perhaps this is somehow solved?

**Comment by phhusson** [comment] 2020-01-10 15:04
On which GSI?

Do you have /odm/phone.prop ? /vendor/phone.prop?

**Comment by phhusson** [comment] 2020-01-10 15:05
Probably a duplicate of #984

**Comment by Alkalainov** [comment] 2020-01-10 16:05
Havok 3.0 is now installed, as far as I know your patches are used here. I have vendor/phone.prop and don't have phone.prop in /odm/
![Screenshot_20200110-215909_Root_Explorer](https://user-images.githubusercontent.com/59735576/72167346-2ccf2b00-33f5-11ea-833c-725b05b07cfc.png)
![Screenshot_20200110-215930_Root_Explorer](https://user-images.githubusercontent.com/59735576/72167348-2ccf2b00-33f5-11ea-9a69-4765a03511fe.png)


Sorry for my english

**Comment by CBbht** [comment] 2020-01-10 16:15
See my issue #1062, you'll get idea what's wrong, i think u simply missed the line in build.prop

**Comment by phhusson** [comment] 2020-01-10 16:16
@CBbht no.

@Alkalainov k then that's same as #984 .
Please attach this /vendor/phone.prop; and also the content of /proc/cmdline

**Comment by Alkalainov** [comment] 2020-01-10 16:37
I attach files
[cmdline.txt](https://github.com/phhusson/treble_experimentations/files/4046603/cmdline.txt)

[phone.prop.txt](https://github.com/phhusson/treble_experimentations/files/4046607/phone.prop.txt)

**Comment by Alkalainov** [comment] 2020-01-10 17:46
If I create a phone.prop file in / odm / and enter the data from /vendor/phone.prop into it, will this help?

![Снимок экрана (5)](https://user-images.githubusercontent.com/59735576/72174248-6c9d0f00-3403-11ea-908c-306b2c9a259f.png)
thank you

**Comment by phhusson** [comment] 2020-01-10 18:15
you can try that: copy /vendor/phone.prop to /odm/phone.prop

or edit /system/bin/rw-system.sh and replace /odm/phone.prop to
/vendor/phone.prop

**Comment by Alkalainov** [comment] 2020-01-10 18:59
I tried both options, the second sim did not appear. Maybe  need a reset?

**Comment by phhusson** [comment] 2020-01-10 19:36
It just needs a reboot

Le ven. 10 janv. 2020 à 19:59, Alkalainov <notifications@github.com> a
écrit :

**Comment by Alkalainov** [comment] 2020-01-10 20:02
I installed AOSP 10.0 v209 now I have phone.prop in / odm / and / vendor /, but the second sim does not work unfortunately. Most likely the problem is somewhere else. Thank you for your help

**Comment by Alkalainov** [comment] 2020-01-12 12:17
In AOSP 10 OpenKirin firmware,  2 sims work. Can you tell me where to see how it is implemented?

**Comment by Alkalainov** [comment] 2020-01-13 05:09
the second sim appears if add the line persist.radio.multisim.config = dsds to /system/build.prop

**Comment by Alkalainov** [comment] 2020-01-13 06:07
I added the line **persist.radio.multisim.config = dsds**  to **/vendor/build.prop**  the second sim works

**Closed** 2020-01-13 06:07 UTC
