### ISSUE TITLE
[Xiaomi A2 Lite]: Menu adaptive brightness is not shown

### ISSUE THREAD

**Issue by schweppi** [phhusson/treble_experimentations#229] opened 2018-10-02 04:32 UTC
Menu adaptive brightness is not shown. Manully controlling of brightness via slider is working.
Affected:
- Oreo - v25 (works in stock oreo Rom - September Patch)
- Pie - v105

**Comment by phhusson** [comment] 2018-10-02 07:45
Duplicate of #226

**Comment by mesilliac** [comment] 2018-10-21 12:29
I can confirm this is fixed by https://github.com/phhusson/vendor_hardware_overlay/pull/32

**Closed** 2019-05-18 20:04 UTC
Labels: triaged
