### ISSUE TITLE
Huawei P20: Fingerprint sensor is broken

### ISSUE THREAD

**Issue by ondrejloska** [phhusson/treble_experimentations#39] opened 2018-05-17 16:06 UTC
On Huawei P20, the fingerprint sensor is broken

Original post:
Fingerprint sensor (not detected in setup and cannot finish configuration in the device settings)
Haptic sensor (the "home" and gestures button is not working at all)
"Cast mode" is broken as well
Apps are crashing sometimes if you start using them too early.
If fresh flash, you need to remove all data and clear cache before downloading apps from PlayStore.

**Comment by phhusson** [comment] 2018-05-20 10:25
Lineage have fixes for those:
https://github.com/berkeley-dev/android_device_huawei_kirin970-common/commit/87f107ba41412a32ad4e28485c38c509420e443a#diff-1afe12f7256573ec622317ea4f75d6a6

**Comment by Edsol** [comment] 2018-08-05 08:04
I don't understand, the fix has been included in the new updates? I still have the same problem and I have installed yesterday latest release.

**Comment by phhusson** [comment] 2018-08-05 08:06
No there is still no fix for this included.
But this bug is a duplicate of another already opened bug, and you can see
it is still open

Le 5 août 2018 10:04, "Edsol" <notifications@github.com> a écrit :

I don't understand, the fix has been included in the new updates? I still
have the same problem and I have installed yesterday latest release.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/phhusson/treble_experimentations/issues/39#issuecomment-410503381>,
or mute the thread

**Comment by phhusson** [comment] 2019-12-16 19:33
This has now been fixed in both pie and Q branches

**Closed by phhusson** 2019-12-16 19:33 UTC
Labels: bug, good first issue
