### ISSUE TITLE
Mi Mix Fold: Inside screen doesn't shut off when folding

### ISSUE THREAD

**Issue by LeOS-GSI** [phhusson/treble_experimentations#1956] opened 2021-08-06 11:32 UTC
Mi Mix Fold: Inside screen doesn't shut off when folding, On MiUI is an Option for 'shut off screen when folding' This feature is missing on A11 GSI

**Comment by phhusson** [comment] 2021-08-15 14:54
I consider this a dupe of #1955

**Closed by phhusson** 2021-08-15 14:54 UTC
