### ISSUE TITLE
[HTC U11+] Incall Audio Issue

### ISSUE THREAD

**Issue by aldaris565** [phhusson/treble_experimentations#48] opened 2018-05-20 14:39 UTC
The Incall Audio is coming through the speakers 
[audio.zip](https://github.com/phhusson/treble_experimentations/files/2020395/audio.zip)

**Comment by jinbolx** [comment] 2018-05-21 05:55
earphone also doesnt work

**Comment by phhusson** [comment] 2018-05-21 22:01
Can you link me to a file dump of your system and vendor?

**Comment by edwkmho** [comment] 2018-05-27 15:46
@phhusson do you mean the link to stock system and vendor files?

**Comment by edwkmho** [comment] 2018-05-29 13:54
I will upload file boot, system, vendor partition of stock rom.
Vendor HTC U11+ 1.24.400.2
https://drive.google.com/open?id=1oVjQvMKxKhc46_FZ-Ljn89oJ3vPsbARj
RUU 1.24.400.2
https://androidfilehost.com/?fid=745849072291700125
system.img (1.24.400.3) .
https://drive.google.com/open?id=1gX75ZTPx5g_Esov9wyKhh4Rc9V24XG5G
Vendor 1.24.400.3
https://drive.google.com/open?id=1e_aCJAiE7Zq7jnu0sKK8TY3HtUE2jdG1
Boot 1.24.400.3
https://drive.google.com/open?id=1QDrWTdYNhR07X2IRzKRNL59BIx_y3Zjh

Tool for extract RUU htc
https://forum.xda-developers.com/chef-central/android/tool-universal-htc-ruu-rom-decryption-t3382928
cmd:RUU_Decrypt_Tool.exe name ruu.zip

**Comment by edwkmho** [comment] 2018-06-05 17:07
I found this in the U11+ source file where the kernel config mentioned the audio amplifier hardware below :
#HTC_AUD_START
CONFIG_SND_SOC_TAS2557_STEREO=y
CONFIG_HTC_AUD_OCM=y
CONFIG_HTC_DEBUG_DSP=n
#HTC_AUD_END

I am please to attached the config file for your reference. Hope with this information you can help to solve the in-cal audio only direct to speaker instead to earphone.
[htc_ocm_defconfig.zip](https://github.com/phhusson/treble_experimentations/files/2073278/htc_ocm_defconfig.zip)

**Comment by drksnw** [comment] 2018-07-08 20:21
@phhusson I noticed that /system/build.prop differs a lot from /vendor/build.prop. Isn't that related ?

Sorry if this is unrelated, it has been a lot if time since I've touched at Android's core, and I don't really know how Treble works 😅

But it would be really nice if it helps to fix this issue, because other things, like data connection, are really working better in your AOSP rom than in stock.

Best regards.

**Comment by phhusson** [comment] 2018-07-09 07:02
system/build.prop and vendor/build.prop are expected to be totally different

Ok, I'd forgotten what was the actual issue
So the issue is that stock ROM uses audio_policy.conf, which is deprecated as of Treble, it should be audio_policy_configuration.xml
HTC U11+'s vendor does contain one audio_policy_configuration.xml, but that's a dummy one.

So what needs to be done is to rewrite audio_policy.conf into a xml

**Comment by drksnw** [comment] 2018-07-09 08:17
Ok cool, need some help with that ?

**Comment by drksnw** [comment] 2018-07-09 17:20
Thanks @phhusson, I managed to get the earpiece working in call, and Bluetooth audio 😉 

Here are the files if someone else wants to do it (It's a quick and dirty fix, please apologise me...)

[audio_policy_configuration.xml](https://gist.github.com/drksnw/032d2a627844f20aeb6b6fd6b3dc6ab8)

[primary_audio_policy_configuration.xml](https://gist.github.com/drksnw/0b09afa6f98b8afa8ea11ea9c650dd97)

[a2dp_audio_policy_configuration.xml](https://gist.github.com/drksnw/cd7bfc9a24228b858e03690f32fc6647)

In order to modify theses files, you'll need to have root and remount /vendor as read/write.
This is done with the following command :

``bash
# mount -o remount,rw /dev/block/platform/soc/1da4000.ufshc/by-name/vendor
``

(your device path might be different, check /proc/mounts to know yours.

And then modify the files with a `cat <<EOF > file_name`. Be sure to make backups before overwriting anything 😉 

Best regards,

**Comment by phhusson** [comment] 2018-07-09 17:33
Cool! And there I was thinking it would require heavy work, doing ioctl
with kernel and stuff, it's good you ping-ed me again :-)

Do you really need to change the three files?
What are the changes in the global file and in a2dp file?
Try to enable the other audio outputs (I wonder if you can get DSD to
work), I'll integrate it then.

**Comment by drksnw** [comment] 2018-07-10 07:02
In theory, you could just have all the files in audio_policy_configuration.xml. But as it already imports configuration from primary_audio_policy_configuration.xml, I thought that it was cleaner to put a2dp related configuration in a separated file (which does not exists...)

So the change in the global file was just to add the import line for a2dp configuration.

I'll try to work on DSD tonight, will keep you updated about that :wink:

**Comment by edwkmho** [comment] 2018-07-11 13:48
thanks drksnw for your effort.

I have some audio config files grab from google Pixel 2 rom. I assumed that the audio setup in Pixel 2 similar to U11+. 
[Audio XML.zip](https://github.com/phhusson/treble_experimentations/files/2184721/Audio.XML.zip)

**Comment by edwkmho** [comment] 2018-07-27 05:07
@phhusson
If you don't mind me asking how would you integrate. I want to tried build AOSP with different configuration files.

Those Audio configuration files attached was pulled from android latest factory image for Pixel 2.

**Comment by RobertKoval** [comment] 2018-08-18 23:01
Some news ?

**Comment by tykoh764** [comment] 2018-09-21 18:38
Hi @phhusson, 
is there any news on how to resolve this bug? Issue is still present in latest v25

**Comment by phhusson** [comment] 2018-10-02 22:44
@drksnw I guess it's really time I include your patch. Did you do some updates?
Do I include those files as is?
Does it work on Pie as well?

**Comment by tykoh764** [comment] 2018-10-13 13:34
@phhusson Once the files have been pushed into the /vendor, the bug will be resolved. I'm not sure whether it will work on Pie, as I am unable to boot into Pie at all. Sry, I'm not currently able to test the rom at the moment.

**Comment by phhusson** [comment] 2019-12-16 19:39
Ok i'll consider this one to be a vendor bug, and I won't fix it.

For users passing by, please refer to [this message](https://github.com/phhusson/treble_experimentations/issues/48#issuecomment-403554459) to fix this issue

**Closed by phhusson** 2019-12-16 19:39 UTC
Labels: triaged

**Comment by 7HE-W0R1D** [comment] 2020-01-13 02:57
> Thanks @phhusson, I managed to get the earpiece working in call, and Bluetooth audio working 😉
> 
> Here are the files if someone else wants to do it (It's a quick and dirty fix, please apologise me...)
> 
> [audio_policy_configuration.xml](https://gist.github.com/drksnw/032d2a627844f20aeb6b6fd6b3dc6ab8)
> 
> [primary_audio_policy_configuration.xml](https://gist.github.com/drksnw/0b09afa6f98b8afa8ea11ea9c650dd97)
> 
> [a2dp_audio_policy_configuration.xml](https://gist.github.com/drksnw/cd7bfc9a24228b858e03690f32fc6647)
> 
> In order to modify theses files, you'll need to have root and remount /vendor as read/write.
> This is done with the following command :
> 
> ```shell
> # mount -o remount,rw /dev/block/platform/soc/1da4000.ufshc/by-name/vendor
> ```
> 
> (your device path might be different, check /proc/mounts to know yours.
> 
> And then modify the files with a `cat <<EOF > file_name`. Be sure to make backups before overwriting anything 😉
> 
> Best regards,
@drksnw 
sorry to bother but how did you exactly use the command `cat <<EOF > file_name`? 
just type this command right after mount vendor?
what do I use to replace the "file_name" in cat command?
btw I found something like"vendor/etc/audio" in /proc/mounts is that useful?
I really want to get my U11+ to play music over bluetooth, but I'm really a noob in things like this.
Thanks in advance!

**Comment by 7HE-W0R1D** [comment] 2020-01-13 04:46
Thanks a lot for your scripts!!!! I wont have to bring another phone with me to listen to songs.
For the method, I tried yours but the "vendor" is neither a folder or an editable file, it has no extension so none of my apps can edit it.
I solved by copying those three files to /system/etc and reboot the phone, then everything is OK.
👍

**Comment by jeanrivera** [comment] 2020-05-20 09:25
@drksnw I am having a similar issue I can make calls and video calls on Bluetooth, but music and videos play only thru speakers on HTC U12+, I would like try your fix, but not sure it will work, what would be your recommendation?

**Comment by drksnw** [comment] 2020-05-27 12:33
Hi @jeanrivera, I don't really know the differences between the U11 and the U12, but as the modifications doesn't rely on specific hardware, I think it might work as is. Just make sure to backup your actual configuration before :wink:

**Comment by jeanrivera** [comment] 2020-05-27 12:37
@drksnw thanks for the reply, if I understand correctly I just need to replace those 3 files in my vendor partition inside the etc folder correct?

**Comment by drksnw** [comment] 2020-05-27 13:34
@jeanrivera you should have these files (or at least audio_policy_configuration.xml) directly in the /vendor folder if I recall it correctly. The configuration should be applied after a reboot

**Comment by usman0tahir** [comment] 2020-06-11 18:50
@drksnw what about the other 2 files? do we copy them to /vendor or /vendor/etc/ ?

**Comment by 7HE-W0R1D** [comment] 2020-09-01 13:48
@drksnw Hi! I'm still using my U11+ and I noticed some issues after I patched your files. Camera apps won't record sound when taking videos, and the usb earphones are not working. Are they possible to fix? If so, I'm really happy to help out.
