### ISSUE TITLE
AOPS 10 v204 mi9 se FOD still not working

### ISSUE THREAD

**Issue by Mhystes** [phhusson/treble_experimentations#894] opened 2019-11-12 13:13 UTC
I've just clean flashed the v204 and still no FOD on mi 9 SE. ( Vendor 11.04 EU )

As far as i use the rom everything works good. (GCAM is working great and the v204 correct the HDR bugs on it)

**Comment by phhusson** [comment] 2019-11-12 20:25
Dupe of #859

**Closed by phhusson** 2019-11-12 20:25 UTC
