### ISSUE TITLE
[Blackview Bv9600pro] Loudspeaker not working

### ISSUE THREAD

**Issue by Giannhsniko** [phhusson/treble_experimentations#1218] opened 2020-04-01 12:24 UTC
i installed the lastest version AOSP 10.0 v214 ""system-quack-arm-aonly-gapps.img.xz""

Camera wifi screen bt all the basic staff working but i can not manage to get loudspeaker playing.
*earpice working
*call sound working
*media works
*bt audio works
-Loud speaker not workig in any case.

Do you need any logcat or some stock rom files to provide so this issue can be resolved? 
Thanks !

**Comment by phhusson** [comment] 2020-04-01 13:48
Duplicate of #417

**Closed by phhusson** 2020-04-01 13:48 UTC
